# Generated by Django 6.0.3 on 2026-05-12 08:20

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


def backfill_hardened_fields(apps, schema_editor):
    Lawyer = apps.get_model('main', 'Lawyer')
    Booking = apps.get_model('main', 'Booking')
    Payment = apps.get_model('main', 'Payment')

    now = django.utils.timezone.now()
    Lawyer.objects.filter(is_verified=True).update(verification_status='approved', verified_at=now)
    Lawyer.objects.filter(is_verified=False).update(verification_status='pending')

    for booking in Booking.objects.select_related('lawyer').all():
        payment_amount = Payment.objects.filter(booking_id=booking.id).values_list('amount', flat=True).first()
        booking.price_snapshot = payment_amount or booking.lawyer.fee
        booking.duration_minutes = booking.duration_minutes or 30
        booking.timezone_name = booking.timezone_name or 'Asia/Kolkata'
        booking.save(update_fields=['price_snapshot', 'duration_minutes', 'timezone_name'])

    for payment in Payment.objects.all():
        if not payment.payment_reference:
            payment.payment_reference = uuid.uuid4()
            payment.save(update_fields=['payment_reference'])


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_lawyer_city'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(blank=True, max_length=20)),
                ('to_status', models.CharField(max_length=20)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClientCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('title', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In progress'), ('closed', 'Closed')], db_index=True, default='open', max_length=20)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='LawyerAvailabilityBreak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('reason', models.CharField(blank=True, max_length=120)),
            ],
            options={
                'ordering': ['start_time'],
            },
        ),
        migrations.CreateModel(
            name='LawyerBlockedDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('date', models.DateField()),
                ('reason', models.CharField(blank=True, max_length=160)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='LegalDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('title', models.CharField(max_length=160)),
                ('file', models.FileField(upload_to='case_documents/')),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived'), ('flagged', 'Flagged')], db_index=True, default='active', max_length=20)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='booking',
            name='client_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='consultation_mode',
            field=models.CharField(choices=[('chat', 'Chat'), ('video', 'Video'), ('phone', 'Phone')], default='chat', max_length=20),
        ),
        migrations.AddField(
            model_name='booking',
            name='duration_minutes',
            field=models.PositiveSmallIntegerField(default=30, validators=[django.core.validators.MinValueValidator(15), django.core.validators.MaxValueValidator(240)]),
        ),
        migrations.AddField(
            model_name='booking',
            name='lawyer_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='meeting_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='price_snapshot',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='booking',
            name='timezone_name',
            field=models.CharField(default='Asia/Kolkata', max_length=64),
        ),
        migrations.AddField(
            model_name='lawyer',
            name='suspended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lawyer',
            name='verification_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='lawyer',
            name='verification_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('under_review', 'Under review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('suspended', 'Suspended')], db_index=True, default='pending', max_length=30),
        ),
        migrations.AddField(
            model_name='lawyer',
            name='verification_submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lawyer',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lawyeravailability',
            name='slot_duration_minutes',
            field=models.PositiveSmallIntegerField(default=30, validators=[django.core.validators.MinValueValidator(15), django.core.validators.MaxValueValidator(240)]),
        ),
        migrations.AddField(
            model_name='lawyeravailability',
            name='timezone_name',
            field=models.CharField(default='Asia/Kolkata', max_length=64),
        ),
        migrations.AddField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('general', 'General'), ('booking', 'Booking'), ('payment', 'Payment'), ('chat', 'Chat'), ('verification', 'Verification'), ('moderation', 'Moderation')], default='general', max_length=30),
        ),
        migrations.AddField(
            model_name='notification',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High')], default='normal', max_length=20),
        ),
        migrations.AddField(
            model_name='notification',
            name='read_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='currency',
            field=models.CharField(default='INR', max_length=3),
        ),
        migrations.AddField(
            model_name='payment',
            name='idempotency_key',
            field=models.CharField(blank=True, db_index=True, max_length=120),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_reference',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='payment',
            name='provider_order_id',
            field=models.CharField(blank=True, db_index=True, max_length=120),
        ),
        migrations.AddField(
            model_name='payment',
            name='provider_payment_id',
            field=models.CharField(blank=True, db_index=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded'), ('rescheduled', 'Rescheduled')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('awaiting_verification', 'Awaiting verification'), ('success', 'Success'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=30),
        ),
        migrations.RunPython(backfill_hardened_fields, migrations.RunPython.noop),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['client', 'status', 'appointment_date'], name='booking_client_status_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['lawyer', 'status', 'appointment_date', 'appointment_time'], name='booking_lawyer_slot_idx'),
        ),
        migrations.AddIndex(
            model_name='chat',
            index=models.Index(fields=['client', 'updated_at'], name='chat_client_updated_idx'),
        ),
        migrations.AddIndex(
            model_name='chat',
            index=models.Index(fields=['lawyer', 'updated_at'], name='chat_lawyer_updated_idx'),
        ),
        migrations.AddIndex(
            model_name='lawyer',
            index=models.Index(fields=['verification_status', 'is_verified'], name='lawyer_verification_idx'),
        ),
        migrations.AddIndex(
            model_name='lawyer',
            index=models.Index(fields=['category', 'city'], name='lawyer_category_city_idx'),
        ),
        migrations.AddIndex(
            model_name='lawyer',
            index=models.Index(fields=['rating_avg', 'review_count'], name='lawyer_rating_idx'),
        ),
        migrations.AddIndex(
            model_name='lawyeravailability',
            index=models.Index(fields=['lawyer', 'weekday', 'is_active'], name='availability_lookup_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['chat', 'timestamp'], name='message_chat_time_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['chat', 'is_read'], name='message_chat_read_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'is_read', 'created_at'], name='notification_user_read_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['notification_type', 'priority'], name='notification_type_priority_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['payment_status', 'created_at'], name='payment_status_created_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['lawyer', 'created_at'], name='review_lawyer_created_idx'),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['pending', 'confirmed'])), fields=('lawyer', 'appointment_date', 'appointment_time'), name='unique_active_lawyer_booking_slot'),
        ),
        migrations.AddConstraint(
            model_name='lawyeravailability',
            constraint=models.CheckConstraint(condition=models.Q(('end_time__gt', models.F('start_time'))), name='availability_end_after_start'),
        ),
        migrations.AddField(
            model_name='bookingstatushistory',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking_status_changes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bookingstatushistory',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='main.booking'),
        ),
        migrations.AddField(
            model_name='clientcase',
            name='booking',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='case', to='main.booking'),
        ),
        migrations.AddField(
            model_name='clientcase',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legal_cases', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='clientcase',
            name='lawyer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_cases', to='main.lawyer'),
        ),
        migrations.AddField(
            model_name='lawyeravailabilitybreak',
            name='availability',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breaks', to='main.lawyeravailability'),
        ),
        migrations.AddField(
            model_name='lawyerblockeddate',
            name='lawyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_dates', to='main.lawyer'),
        ),
        migrations.AddField(
            model_name='legaldocument',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='main.clientcase'),
        ),
        migrations.AddField(
            model_name='legaldocument',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_legal_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='bookingstatushistory',
            index=models.Index(fields=['booking', 'created_at'], name='booking_history_lookup_idx'),
        ),
        migrations.AddIndex(
            model_name='clientcase',
            index=models.Index(fields=['client', 'status'], name='case_client_status_idx'),
        ),
        migrations.AddIndex(
            model_name='clientcase',
            index=models.Index(fields=['lawyer', 'status'], name='case_lawyer_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='lawyeravailabilitybreak',
            constraint=models.CheckConstraint(condition=models.Q(('end_time__gt', models.F('start_time'))), name='availability_break_end_after_start'),
        ),
        migrations.AddConstraint(
            model_name='lawyerblockeddate',
            constraint=models.UniqueConstraint(fields=('lawyer', 'date'), name='unique_lawyer_blocked_date'),
        ),
        migrations.AddIndex(
            model_name='legaldocument',
            index=models.Index(fields=['case', 'status'], name='document_case_status_idx'),
        ),
    ]
