# Generated by Django 6.0.3 on 2026-05-12 09:37

import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_bookingstatushistory_clientcase_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='email_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lawyer',
            name='certificate_file',
            field=models.FileField(blank=True, null=True, upload_to=main.models.certificate_upload_path),
        ),
        migrations.AlterField(
            model_name='legaldocument',
            name='file',
            field=models.FileField(upload_to=main.models.case_document_upload_path),
        ),
        migrations.AlterField(
            model_name='message',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=main.models.chat_file_upload_path),
        ),
    ]
