# Generated by Django 6.0.3 on 2026-05-12 18:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_userprofile_email_verified_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(blank=True, max_length=30)),
                ('to_status', models.CharField(max_length=30)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('idempotency_key', models.CharField(blank=True, max_length=120)),
                ('provider', models.CharField(blank=True, max_length=50)),
                ('provider_event_id', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key', ''), _negated=True), fields=('idempotency_key',), name='unique_payment_idempotency_key'),
        ),
        migrations.AddField(
            model_name='paymentstatushistory',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_status_changes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paymentstatushistory',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='main.payment'),
        ),
        migrations.AddIndex(
            model_name='paymentstatushistory',
            index=models.Index(fields=['payment', 'created_at'], name='payment_history_lookup_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentstatushistory',
            index=models.Index(fields=['provider', 'provider_event_id'], name='payment_provider_event_idx'),
        ),
        migrations.AddConstraint(
            model_name='paymentstatushistory',
            constraint=models.UniqueConstraint(condition=models.Q(('provider_event_id', ''), _negated=True), fields=('provider', 'provider_event_id'), name='unique_payment_provider_event'),
        ),
    ]
