# Generated by Codex on 2026-05-13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0011_paymentstatushistory_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RefundRequest",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, blank=True, null=True)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("currency", models.CharField(default="INR", max_length=3)),
                ("reason", models.CharField(blank=True, max_length=255)),
                ("status", models.CharField(choices=[("requested", "Requested"), ("processing", "Processing"), ("processed", "Processed"), ("failed", "Failed"), ("cancelled", "Cancelled")], default="requested", max_length=20)),
                ("provider", models.CharField(default="Secure Demo", max_length=50)),
                ("provider_refund_id", models.CharField(blank=True, db_index=True, max_length=120)),
                ("idempotency_key", models.CharField(blank=True, db_index=True, max_length=120)),
                ("failure_reason", models.CharField(blank=True, max_length=255)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                ("payment", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="refund_requests", to="main.payment")),
                ("processed_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="processed_refunds", to=settings.AUTH_USER_MODEL)),
                ("requested_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="requested_refunds", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProviderEvent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, blank=True, null=True)),
                ("provider", models.CharField(max_length=50)),
                ("event_id", models.CharField(db_index=True, max_length=120)),
                ("event_type", models.CharField(max_length=80)),
                ("payload_hash", models.CharField(max_length=64)),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("processing_status", models.CharField(choices=[("received", "Received"), ("processed", "Processed"), ("ignored", "Ignored"), ("failed", "Failed")], default="received", max_length=20)),
                ("replay_count", models.PositiveIntegerField(default=0)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                ("error_message", models.CharField(blank=True, max_length=255)),
                ("payment", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="provider_events", to="main.payment")),
                ("refund_request", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="provider_events", to="main.refundrequest")),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RefundStatusHistory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("from_status", models.CharField(blank=True, max_length=20)),
                ("to_status", models.CharField(max_length=20)),
                ("reason", models.CharField(blank=True, max_length=255)),
                ("provider", models.CharField(blank=True, max_length=50)),
                ("provider_event_id", models.CharField(blank=True, max_length=120)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("actor", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="refund_status_changes", to=settings.AUTH_USER_MODEL)),
                ("refund_request", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="status_history", to="main.refundrequest")),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PaymentLedgerEntry",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("entry_type", models.CharField(choices=[("payment_captured", "Payment captured"), ("payment_refunded", "Payment refunded"), ("reconciliation_note", "Reconciliation note")], max_length=30)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("currency", models.CharField(default="INR", max_length=3)),
                ("provider", models.CharField(blank=True, max_length=50)),
                ("provider_event_id", models.CharField(blank=True, max_length=120)),
                ("idempotency_key", models.CharField(blank=True, max_length=120)),
                ("description", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("payment", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="ledger_entries", to="main.payment")),
                ("refund_request", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="ledger_entries", to="main.refundrequest")),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="refundrequest",
            index=models.Index(fields=["payment", "status"], name="refund_payment_status_idx"),
        ),
        migrations.AddIndex(
            model_name="refundrequest",
            index=models.Index(fields=["provider", "provider_refund_id"], name="refund_provider_refund_idx"),
        ),
        migrations.AddConstraint(
            model_name="refundrequest",
            constraint=models.UniqueConstraint(condition=models.Q(("idempotency_key", ""), _negated=True), fields=("idempotency_key",), name="unique_refund_idempotency_key"),
        ),
        migrations.AddConstraint(
            model_name="refundrequest",
            constraint=models.UniqueConstraint(condition=models.Q(("provider_refund_id", ""), _negated=True), fields=("provider", "provider_refund_id"), name="unique_refund_provider_refund"),
        ),
        migrations.AddIndex(
            model_name="providerevent",
            index=models.Index(fields=["provider", "event_id"], name="provider_event_lookup_idx"),
        ),
        migrations.AddIndex(
            model_name="providerevent",
            index=models.Index(fields=["processing_status", "created_at"], name="provider_event_status_idx"),
        ),
        migrations.AddConstraint(
            model_name="providerevent",
            constraint=models.UniqueConstraint(fields=("provider", "event_id"), name="unique_provider_event"),
        ),
        migrations.AddIndex(
            model_name="refundstatushistory",
            index=models.Index(fields=["refund_request", "created_at"], name="refund_history_lookup_idx"),
        ),
        migrations.AddIndex(
            model_name="refundstatushistory",
            index=models.Index(fields=["provider", "provider_event_id"], name="refund_provider_event_idx"),
        ),
        migrations.AddIndex(
            model_name="paymentledgerentry",
            index=models.Index(fields=["payment", "created_at"], name="ledger_payment_lookup_idx"),
        ),
        migrations.AddIndex(
            model_name="paymentledgerentry",
            index=models.Index(fields=["provider", "provider_event_id"], name="ledger_provider_event_idx"),
        ),
        migrations.AddConstraint(
            model_name="paymentledgerentry",
            constraint=models.UniqueConstraint(condition=models.Q(("provider_event_id", ""), _negated=True), fields=("provider", "provider_event_id", "entry_type"), name="unique_ledger_provider_event_type"),
        ),
        migrations.AddConstraint(
            model_name="paymentledgerentry",
            constraint=models.UniqueConstraint(condition=models.Q(("idempotency_key", ""), _negated=True), fields=("idempotency_key", "entry_type"), name="unique_ledger_idem_type"),
        ),
    ]
